version: 2
jobs:
  build:
    working_directory: /go/src/github.com/philippwinter/rt-golang
    docker:
      - image: circleci/golang:1.8
    steps:
      - checkout
      - run:
          name: Start test server
          command: go run ./cmd/testserver/main.go
          background: true
      - run:
          name: Validate test server is running
          command: wget --retry-connrefused --waitretry=1 --read-timeout=20 --timeout=5 http://localhost:41414/
      - run:
          name: Build project
          command: go build
      - run:
          name: Execute Unit Tests
          command: go test -v